"""Only Cloudflare may reach the origin, and the rule is testable before it ships.

Putting a hostname behind Cloudflare Access protects the hostname, not the
machine. Access is enforced at Cloudflare's edge, so a request that never goes
through the edge is never subject to it — and the origin address of this
deployment is already public, because a sibling hostname on the same zone
publishes an A record straight to it. Anyone can therefore open a connection to
the address, send ``Host: agent.youtab.io``, and be talking to the application
with no Access check anywhere in the path.

That is not a hypothetical about a misconfigured edge. It is the default
behaviour of every origin that listens on a public interface, and it is why
"we put Access in front of it" is not by itself an access control.

So the origin refuses anything that did not arrive through the edge. This
module holds that decision as data plus a function, which is what lets it be
tested now — before any of it is installed, and without a live host to probe.
:func:`render_nginx_allowlist` emits the same ranges the function checks, from
the same constant, so the configuration and the test cannot disagree about what
is allowed.

Defence in depth, not instead of
--------------------------------
An address allowlist is the *outer* control and deliberately the weaker one. It
is spoofable in principle, it goes stale when the published ranges change, and
it says nothing about who the caller is. It exists to stop the trivially
bypassable case. Authenticated Origin Pulls — the edge presenting a client
certificate the origin verifies — is the control that actually proves the
request came from Cloudflare, and :func:`render_nginx_server_block` emits the
directives for it alongside the allowlist. Neither replaces Cloudflare Access
deciding *which people* may through; all three sit in series.
"""

from __future__ import annotations

import ipaddress
from typing import Final, Iterable

#: Cloudflare's published edge ranges, pinned rather than fetched at runtime: an
#: origin that phoned home for its own allowlist would fail open the moment that
#: request failed, which is precisely when it matters. Refresh deliberately, by
#: re-running the documented fetch and committing the diff, so a change to who
#: may reach the origin is a reviewable commit rather than a network event.
#:
#:   curl -s https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6
CLOUDFLARE_RANGES: Final[tuple[str, ...]] = (
    # IPv4
    "173.245.48.0/20", "103.21.244.0/22", "103.22.200.0/22", "103.31.4.0/22",
    "141.101.64.0/18", "108.162.192.0/18", "190.93.240.0/20", "188.114.96.0/20",
    "197.234.240.0/22", "198.41.128.0/17", "162.158.0.0/15", "104.16.0.0/13",
    "104.24.0.0/14", "172.64.0.0/13", "131.0.72.0/22",
    # IPv6
    "2400:cb00::/32", "2606:4700::/32", "2803:f800::/32", "2405:b500::/32",
    "2405:8100::/32", "2a06:98c0::/29", "2c0f:f248::/32",
)

_NETWORKS: Final[tuple[ipaddress.IPv4Network | ipaddress.IPv6Network, ...]] = tuple(
    ipaddress.ip_network(cidr) for cidr in CLOUDFLARE_RANGES
)


def is_cloudflare_ip(address: str) -> bool:
    """True if ``address`` is inside a published Cloudflare edge range.

    An unparseable address is not Cloudflare. Returning False rather than
    raising keeps the fail-closed direction: a caller that cannot be placed is
    refused, never admitted because the check errored.
    """
    try:
        candidate = ipaddress.ip_address(address)
    except ValueError:
        return False
    return any(candidate in network for network in _NETWORKS)


def render_nginx_allowlist(ranges: Iterable[str] = CLOUDFLARE_RANGES) -> str:
    """Emit ``allow``/``deny`` directives for an nginx server block.

    Generated from :data:`CLOUDFLARE_RANGES` rather than maintained by hand, so
    the configuration installed on the host and the rule this module tests are
    the same list. A hand-copied allowlist drifts, and it drifts silently in the
    permissive direction.
    """
    lines = [f"    allow {cidr};" for cidr in ranges]
    # The closing deny is what makes the preceding lines an allowlist rather
    # than a set of exceptions to an open door.
    lines.append("    deny all;")
    return "\n".join(lines)


def render_nginx_server_block(
    *,
    server_name: str,
    upstream: str,
    certificate: str,
    certificate_key: str,
    origin_pull_ca: str,
) -> str:
    """A complete origin server block: TLS, origin pulls, allowlist, loopback upstream.

    ``upstream`` is expected to be a loopback address. The application binds
    only to loopback, so the reverse proxy is the sole route to it and every
    request is subject to the controls in this block.
    """
    return f"""# Generated by youtab_runtime.origin_protection — edit the generator, not this.
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name {server_name};

    ssl_certificate     {certificate};
    ssl_certificate_key {certificate_key};

    # Authenticated Origin Pulls. The edge presents a client certificate and
    # the origin verifies it, which is the control that actually proves a
    # request came from Cloudflare rather than merely from an address that
    # currently belongs to it.
    ssl_client_certificate {origin_pull_ca};
    ssl_verify_client on;

    # Outer control: refuse anything not arriving from a published edge range,
    # including a direct connection to this host's address carrying a forged
    # Host header.
{render_nginx_allowlist()}

    location / {{
        proxy_pass http://{upstream};
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # The dashboard uses WebSockets for the terminal and streaming replies.
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }}

    # Readiness, reachable only through the same controls as everything else.
    # A health endpoint exempted from the allowlist is an unauthenticated
    # window into whether the service is up and which version is running.
    location = /api/health {{
        proxy_pass http://{upstream}/api/health;
        access_log off;
    }}
}}
"""
