"""Only Cloudflare may reach the origin, and the rule is testable before it ships.

Putting a hostname behind Cloudflare Access protects the hostname, not the
machine. Access is enforced at Cloudflare's edge, so a request that never goes
through the edge is never subject to it — and the origin address of this
deployment is already public, because a sibling hostname on the same zone
publishes an A record straight to it. Anyone can therefore open a connection to
the address, send ``Host: agent.youtab.io``, and be talking to the application
with no Access check anywhere in the path.

That is not a hypothetical about a misconfigured edge. It is the default
behaviour of every origin that listens on a public interface, and it is why
"we put Access in front of it" is not by itself an access control.

So the origin refuses anything that did not arrive through the edge. This
module holds that decision as data plus a function, which is what lets it be
tested now — before any of it is installed, and without a live host to probe.
:func:`render_nginx_allowlist` emits the same ranges the function checks, from
the same constant, so the configuration and the test cannot disagree about what
is allowed.

Defence in depth, not instead of
--------------------------------
An address allowlist is the *outer* control and deliberately the weaker one. It
is spoofable in principle, it goes stale when the published ranges change, and
it says nothing about who the caller is. It exists to stop the trivially
bypassable case. Authenticated Origin Pulls — the edge presenting a client
certificate the origin verifies — is the control that actually proves the
request came from Cloudflare, and :func:`render_nginx_server_block` emits the
directives for it alongside the allowlist. Neither replaces Cloudflare Access
deciding *which people* may through; all three sit in series.
"""

from __future__ import annotations

import ipaddress
from typing import Final, Iterable

#: Cloudflare's published edge ranges, pinned rather than fetched at runtime: an
#: origin that phoned home for its own allowlist would fail open the moment that
#: request failed, which is precisely when it matters. Refresh deliberately, by
#: re-running the documented fetch and committing the diff, so a change to who
#: may reach the origin is a reviewable commit rather than a network event.
#:
#:   curl -s https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6
CLOUDFLARE_RANGES: Final[tuple[str, ...]] = (
    # IPv4
    "173.245.48.0/20", "103.21.244.0/22", "103.22.200.0/22", "103.31.4.0/22",
    "141.101.64.0/18", "108.162.192.0/18", "190.93.240.0/20", "188.114.96.0/20",
    "197.234.240.0/22", "198.41.128.0/17", "162.158.0.0/15", "104.16.0.0/13",
    "104.24.0.0/14", "172.64.0.0/13", "131.0.72.0/22",
    # IPv6
    "2400:cb00::/32", "2606:4700::/32", "2803:f800::/32", "2405:b500::/32",
    "2405:8100::/32", "2a06:98c0::/29", "2c0f:f248::/32",
)

_NETWORKS: Final[tuple[ipaddress.IPv4Network | ipaddress.IPv6Network, ...]] = tuple(
    ipaddress.ip_network(cidr) for cidr in CLOUDFLARE_RANGES
)


def is_cloudflare_ip(address: str) -> bool:
    """True if ``address`` is inside a published Cloudflare edge range.

    An unparseable address is not Cloudflare. Returning False rather than
    raising keeps the fail-closed direction: a caller that cannot be placed is
    refused, never admitted because the check errored.
    """
    try:
        candidate = ipaddress.ip_address(address)
    except ValueError:
        return False
    return any(candidate in network for network in _NETWORKS)


def render_nginx_allowlist(ranges: Iterable[str] = CLOUDFLARE_RANGES) -> str:
    """Emit ``allow``/``deny`` directives for an nginx server block.

    Generated from :data:`CLOUDFLARE_RANGES` rather than maintained by hand, so
    the configuration installed on the host and the rule this module tests are
    the same list. A hand-copied allowlist drifts, and it drifts silently in the
    permissive direction.
    """
    lines = [f"    allow {cidr};" for cidr in ranges]
    # The closing deny is what makes the preceding lines an allowlist rather
    # than a set of exceptions to an open door.
    lines.append("    deny all;")
    return "\n".join(lines)


def render_nginx_server_block(
    *,
    server_name: str,
    upstream: str,
    certificate: str,
    certificate_key: str,
    origin_pull_ca: str,
) -> str:
    """A complete origin server block: TLS, origin pulls, allowlist, loopback upstream.

    ``upstream`` is expected to be a loopback address. The application binds
    only to loopback, so the reverse proxy is the sole route to it and every
    request is subject to the controls in this block.
    """
    return f"""# Generated by youtab_runtime.origin_protection — edit the generator, not this.
server {{
    # HTTP/2 on the listen directive. The `http2 on;` form is nginx >= 1.25.1
    # only, and Ubuntu 20.04/22.04 LTS ship 1.18/1.24 -- the deployment target.
    # Emitting the newer spelling made `nginx -t` fail with `unknown directive`
    # and the block had to be corrected by hand on the host, which is the
    # divergence this generator exists to prevent.
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {server_name};

    ssl_certificate     {certificate};
    ssl_certificate_key {certificate_key};

    # The TLS floor, stated rather than inherited. Omitting `ssl_protocols`
    # does not mean "modern TLS"; it means nginx's compiled default, and on
    # 1.18 -- the deployment target -- that default is
    # `ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`. So the directive's ABSENCE was
    # the exposure: this origin served TLS 1.0 and TLS 1.1, both deprecated by
    # RFC 8996, on a control plane that can start and stop the gateway.
    #
    # Written inside the server block rather than once in `http {{}}` on
    # purpose. An http-level floor is inherited only by server blocks that do
    # not set their own, so it is one unrelated `include` away from being
    # silently overridden -- and the failure is invisible, because the
    # weakened block still starts and still serves. A floor stated here is a
    # floor this artifact can be read for and tested against.
    ssl_protocols TLSv1.2 TLSv1.3;

    # Authenticated Origin Pulls. The edge presents a client certificate and
    # the origin verifies it, which is the control that actually proves a
    # request came from Cloudflare rather than merely from an address that
    # currently belongs to it.
    ssl_client_certificate {origin_pull_ca};
    ssl_verify_client on;

    # Outer control: refuse anything not arriving from a published edge range,
    # including a direct connection to this host's address carrying a forged
    # Host header.
{render_nginx_allowlist()}

    location / {{
        proxy_pass http://{upstream};

        # Every one of these is SET, not appended, and none is derived from a
        # value the client chose. `$host` is the server_name this block
        # matched, so the upstream sees the governed public hostname and can
        # build OAuth callbacks and absolute URLs from it. `X-Forwarded-Proto`
        # is the literal `https` rather than `$scheme` because this block only
        # ever terminates TLS -- reflecting the scheme would let a
        # misconfiguration downgrade it.
        #
        # `X-Forwarded-For` uses `$proxy_add_x_forwarded_for`, which appends
        # the peer to any inbound value. That is correct here and only here:
        # the `deny all` above means the peer is always a Cloudflare edge
        # address, so the inbound chain is the edge's own and not attacker
        # input. Behind an untrusted network this would have to be
        # `$remote_addr`.
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # The dashboard uses WebSockets for the terminal and streaming replies.
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }}

    # Readiness, reachable only through the same controls as everything else.
    # A health endpoint exempted from the allowlist is an unauthenticated
    # window into whether the service is up and which version is running.
    location = /api/health {{
        proxy_pass http://{upstream}/api/health;
        access_log off;
    }}
}}
"""


#: Where the rendered artifact is committed, relative to the repository root.
#: Named here rather than in the script and again in the test, so the two
#: cannot come to disagree about which file is the generated one.
AGENT_ORIGIN_CONF_PATH: Final[str] = "infrastructure/nginx/agent.youtab.io.conf"

#: The arguments the committed artifact was rendered with. These were
#: previously written out at each call site -- the script that regenerates the
#: file, and the test that checks it -- which is a drift seam of exactly the
#: kind this module exists to close: a test rendering `ssl_verify_client` from
#: one set of paths and the host running another would agree with itself and
#: prove nothing about what is deployed.
AGENT_ORIGIN_PARAMETERS: Final[dict[str, str]] = {
    "server_name": "agent.youtab.io",
    "upstream": "127.0.0.1:8081",
    "certificate": "/etc/ssl/cloudflare/agent.youtab.io.crt",
    "certificate_key": "/etc/ssl/cloudflare/agent.youtab.io.key",
    "origin_pull_ca": "/etc/ssl/cloudflare/origin-pull-ca.pem",
}


def render_agent_origin_conf() -> str:
    """The exact text of :data:`AGENT_ORIGIN_CONF_PATH`.

    The committed file is this function's return value and nothing else. It is
    checked byte-for-byte in CI, so a hand-edit on the artifact fails rather
    than quietly becoming the thing that is deployed -- which is how the
    ``http2 on;`` correction happened on the host last time.
    """
    return render_nginx_server_block(**AGENT_ORIGIN_PARAMETERS)
