#!/usr/bin/env python3
"""Generate tools/wakewords/MODEL_CARD.md from the run that produced the model.

Written rather than hand-maintained for one reason: a hand-written card drifts.
Every number here comes from ``training.json`` and ``measurements.json``, and
the hashes are computed from the artifacts on disk at the moment the card is
written, so the card cannot claim a false-accept rate the shipped bytes never
achieved. ``test_wake_word_model_assets.py`` re-checks those hashes, which is
what keeps the two in step afterwards.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Run as a script, not a package: the pipeline stages are invoked directly, so
# the sibling module has to be reachable without an installed distribution.
sys.path.insert(0, str(Path(__file__).resolve().parent))

import assets  # noqa: E402


def _pct(value: float | None) -> str:
    return "—" if value is None else f"{value * 100:.2f}%"


def _sweep_table(table: dict) -> str:
    rows = [
        "| threshold | false reject | false accept | per hour of speech |",
        "|---|---|---|---|",
    ]
    for threshold, row in sorted(table.items()):
        marker = " **(default)**" if threshold == "0.60" else ""
        rows.append(
            f"| {threshold}{marker} | {_pct(row['false_reject_rate'])} "
            f"| {_pct(row['false_accept_rate'])} "
            f"| {row['false_accepts_per_hour']:.2f} |"
        )
    return "\n".join(rows)


def _category_table(row: dict) -> str:
    labels = {
        "near_phrase": "near misses (`hey youtube`, `hey your tab`, `youtab` alone, …)",
        "recorded_speech": "recorded human speech (Speech Commands, held-out speakers)",
        "synthesized_speech": "ordinary synthesized sentences",
        "background_only": "background recordings, no speech",
    }
    rows = ["| negative kind | windows | false accepts | rate |", "|---|---|---|---|"]
    for name, stats in sorted(row["by_category"].items()):
        rows.append(
            f"| {labels.get(name, name)} | {stats['windows']:,} "
            f"| {stats['false_accepts']} | {_pct(stats['false_accept_rate'])} |"
        )
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--training", type=Path, required=True)
    parser.add_argument("--measurements", type=Path, required=True)
    parser.add_argument("--train-stats", type=Path, required=True)
    parser.add_argument("--eval-stats", type=Path, required=True)
    parser.add_argument("--wakewords", type=Path, required=True)
    args = parser.parse_args()

    training = json.loads(args.training.read_text(encoding="utf-8"))
    measured = json.loads(args.measurements.read_text(encoding="utf-8"))
    train_stats = json.loads(args.train_stats.read_text(encoding="utf-8"))
    eval_stats = json.loads(args.eval_stats.read_text(encoding="utf-8"))

    hashes = {
        name: assets.sha256_file(args.wakewords / name)
        for name in ("hey_youtab.onnx", "hey_youtab.tflite")
    }
    (args.wakewords / "SHA256SUMS").write_text(
        "".join(f"{digest}  {name}\n" for name, digest in sorted(hashes.items())),
        encoding="utf-8",
    )

    hyper = training["hyperparameters"]
    default = f"{hyper['operating_threshold']:.2f}"
    onnx = measured["backends"]["onnx"]
    tflite = measured["backends"]["tflite"]
    plateau = onnx[default]["positive_score_plateau"]

    provenance = "\n".join(
        f"| `{a.name}` | {a.license} | `{a.sha256[:16]}…` | {a.attribution} |"
        for a in assets.ALL_ASSETS
    )

    card = f"""# Model card — `hey_youtab`

The wake-word detector Youtab ships. Built by `scripts/wakeword/run_pipeline.sh`
from the pinned, licensed inputs below; no GPU, no private data, no
unlicensed corpus.

Every number on this page was measured on **held-out** data — voices, rooms and
background recordings that training never saw — by streaming audio through
`tools.wake_word._OpenWakeWordEngine`, the same class the CLI, TUI and desktop
app construct. This file is generated by `scripts/wakeword/write_model_card.py`
from the run's own outputs, so it cannot describe a model other than the one
whose hashes it records.

## Artifacts

| file | SHA-256 |
|---|---|
| `hey_youtab.onnx` | `{hashes["hey_youtab.onnx"]}` |
| `hey_youtab.tflite` | `{hashes["hey_youtab.tflite"]}` |

Both are exported from one set of weights. Over
{training["parity"]["windows_compared"]} held-out windows the two backends
differ by at most **{training["parity"]["max_absolute_difference"]:.2e}**
(mean {training["parity"]["mean_absolute_difference"]:.2e}). ONNX is loaded
everywhere except macOS ARM64, where openWakeWord's ONNX embedding model
returns near-zero scores (dscripka/openWakeWord#336) and the runtime switches
to tflite.

## Architecture

| | |
|---|---|
| Input | `{training["parity"]["onnx_input_shape"]}` float32 — openWakeWord embedding frames |
| Output | `{training["parity"]["onnx_output_shape"]}` float32 — probability the phrase just finished |
| Hidden layers | {hyper["hidden"]}, ReLU |
| Parameters | {training["parameters"]:,} |
| Window | {measured["window_seconds"]:.2f} s |

Only the phrase-specific classifier is trained here. The melspectrogram and
speech-embedding front end is upstream openWakeWord, unmodified and pinned.

## Training data

| | windows | source utterances |
|---|---|---|
| positive | {train_stats["positives"]:,} | {train_stats["synthesized_positive_clips"]:,} synthesized clips |
| negative | {train_stats["negatives"]:,} | incl. {train_stats["recorded_negative_clips"]:,} recorded human clips |

Augmented with {train_stats["impulse_responses"]} synthetic room impulse
responses and the background recordings
{", ".join(f"`{n}`" for n in train_stats["background_recordings"])}, at
0–25 dB SNR.

Held out for measurement: {eval_stats["windows"]:,} windows
({eval_stats["positives"]:,} positive, {eval_stats["negatives"]:,} negative)
from speaker pool `[700, 904)`, Speech Commands' own validation and testing
lists, the background recordings
{", ".join(f"`{n}`" for n in eval_stats["background_recordings"])}, and a
separately seeded impulse-response pool.

## Training configuration

| | |
|---|---|
| Seed | {hyper["seed"]} |
| Epochs | {hyper["epochs"]} (selected: {training["selected_epoch"]}) |
| Batch size | {hyper["batch_size"]} |
| Learning rate | {hyper["learning_rate"]} |
| Dropout | {hyper["dropout"]} |
| Negative class weight | {hyper["negative_weight"]} |
| Model selection | false-accept and false-reject at threshold {default}, on a grouped validation split |

## Measured performance

{measured["negative_windows"]:,} negative windows —
{measured["negative_audio_hours"]:.1f} hours of audio — and
{measured["positive_windows"]:,} spoken wake words, through the real engine
with its {measured["confirmation_frames"]}-consecutive-frame confirmation rule.

### ONNX (every platform except macOS ARM64)

{_sweep_table(onnx)}

At the default threshold, by kind of negative:

{_category_table(onnx[default])}

### tflite (macOS ARM64)

{_sweep_table(tflite)}

At the default threshold, by kind of negative:

{_category_table(tflite[default])}

### Score plateau

The engine fires only after {measured["confirmation_frames"]} consecutive
frames over threshold, so a model that spikes for one frame and drops would
score perfectly and never wake. On held-out utterances the score stays over the
default threshold for a median of **{plateau["median_frames_over_threshold"]:.0f}
frames** ({plateau["median_frames_over_threshold"] * 0.08:.2f} s), and for
{plateau["p10_frames_over_threshold"]:.0f} frames at the 10th percentile.

## Licences

| input | licence | SHA-256 | attribution |
|---|---|---|---|
{provenance}

The trained artifacts are derived works of the openWakeWord front end
(Apache-2.0) and of speech from LibriTTS-R and Speech Commands (both CC BY
4.0); all three permit redistribution with attribution, which this file
provides.

## Limitations

* English only, and American English at that — the generator is a US English
  voice model and espeak-ng's `en-us` phonemization.
* Positives are synthesized. Synthetic speech covers speaker, rate and channel
  variation well, but it does not cover every accent, and the false-reject rate
  on a given real speaker may differ from the number above.
* The negatives are read commands and short sentences. Sustained conversation,
  music and television are not represented, so the per-hour figure is a floor
  rather than a promise about a noisy living room.
* Trained for one phrase. Say something else and it will not fire; that is what
  the sherpa engine is for.
"""
    (args.wakewords / "MODEL_CARD.md").write_text(card, encoding="utf-8")
    print(f"wrote {args.wakewords / 'MODEL_CARD.md'}")
    print(f"wrote {args.wakewords / 'SHA256SUMS'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
