#!/usr/bin/env python3
"""Audit the controls that decide what "green" means.

Every other gate in this directory inspects the product. This one inspects
the gates: the workflows that run them, the pins that fix what code those
workflows execute, the ruleset that decides which of them can block a merge,
and the baselines that decide what counts as a finding. A defect here does
not show up as a failing check -- it shows up as a check that stops failing,
which is the one failure mode nothing else in the repository looks for.

Every condition below is one that has actually cost this repository a P1, and
the history is recorded against each so a later reader can judge whether the
rule still earns its place rather than deleting it as noise:

    1. required check nobody produces   A ruleset required the WORKFLOW name
                                        ``CodeQL no-new-findings gate`` and
                                        later ``CodeQL analyze (python, none)``
                                        after `build-mode` renamed the matrix
                                        contexts. GitHub matches required
                                        checks on JOB name, so every pull
                                        request blocked forever waiting on a
                                        status nothing emitted. Three times.

    2. gate that cannot block           ``CodeQL analyze (actions)``,
                                        ``(c-cpp)`` and ``(rust)`` ran and
                                        reported for days while being
                                        advisory, because nothing required
                                        them. A gate nobody requires is a log
                                        line.

    3. split action version             Dependabot bumped
                                        ``codeql-action/init`` to 4.38.2 and
                                        left ``analyze`` on 3.37.9. Since
                                        3.30.4 the non-init steps THROW when
                                        they load a config generated by a
                                        different version, so every run would
                                        have died at ``analyze`` with no SARIF
                                        -- a red gate whose cause is three
                                        steps away from its symptom.

    4. unpinned action                  A floating ``@v4`` silently follows
                                        upstream, so what runs in CI changes
                                        with no commit in this repository.

    5. missing permissions              A workflow with no ``permissions:``
                                        block inherits the token's default,
                                        which on older repository settings is
                                        write-all. The CodeQL workflow needs
                                        ``security-events: write`` and nothing
                                        else.

    6. pull_request_target + PR head    Checking out the pull request's head
                                        under ``pull_request_target`` runs
                                        untrusted code with a write token and
                                        secrets. This is the standard CI
                                        takeover, and no scanner here looked
                                        for it.

    7. gate that cannot fail            ``continue-on-error: true`` on a step
                                        whose job is to fail turns it into a
                                        notification.

    8. baseline without a budget        The severity ratchet lives in the
                                        baseline. A baseline built before it
                                        existed, or regenerated with an older
                                        script, silently removes the control.

    9. CodeQL leg with no baseline      A matrix language with no committed
                                        baseline fails its gate step on every
                                        run with a path error, and the usual
                                        response is to drop the gate.

Each condition fails CLOSED. Where a condition cannot be evaluated -- the
ruleset needs an API token -- it is reported as SKIPPED and never as PASS,
and ``--require-remote`` turns a skip into a failure for CI, where the token
is present and a skip would mean the check silently stopped running.

Usage::

    python scripts/youtab/ci_control_gate.py --root . --json evidence.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

SHA_RE = re.compile(r"^[0-9a-f]{40}$")
VERSION_COMMENT_RE = re.compile(r"#\s*v?\d+(\.\d+)*")

#: Actions from GitHub's own namespaces still get pinned -- the 2025
#: tj-actions/changed-files compromise was a widely trusted third-party action
#: whose tags were rewritten, and nothing about the owner changes the argument.
PIN_EXEMPT_PREFIXES: tuple[str, ...] = ("./", "docker://")

#: A step is treated as a gate when its name or command says so. Used only to
#: decide whether `continue-on-error` is suspicious, so a false positive costs
#: a comment and a false negative costs a silent gate.
GATE_WORDS = ("gate", "test", "lint", "typecheck", "type-check", "audit",
              "scan", "verify", "check")


class Findings:
    """Collects findings so every condition is evaluated before exiting."""

    def __init__(self) -> None:
        self.items: list[dict[str, Any]] = []

    def fail(self, condition: str, where: str, detail: str) -> None:
        self.items.append({"status": "fail", "condition": condition,
                           "where": where, "detail": detail})

    def skip(self, condition: str, detail: str) -> None:
        self.items.append({"status": "skip", "condition": condition,
                           "where": "", "detail": detail})

    @property
    def failures(self) -> list[dict[str, Any]]:
        return [i for i in self.items if i["status"] == "fail"]

    @property
    def skips(self) -> list[dict[str, Any]]:
        return [i for i in self.items if i["status"] == "skip"]


def load_workflows(root: Path) -> dict[Path, dict]:
    import yaml

    out: dict[Path, dict] = {}
    for path in sorted((root / ".github" / "workflows").glob("*.y*ml")):
        try:
            loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001 - an unparseable workflow is a failure
            out[path] = {"__error__": str(exc)}
            continue
        out[path] = loaded if isinstance(loaded, dict) else {"__error__": "not a mapping"}
    return out


def steps_of(job: Any) -> list[dict]:
    if not isinstance(job, dict):
        return []
    return [s for s in (job.get("steps") or []) if isinstance(s, dict)]


def triggers_of(workflow: dict) -> dict:
    # PyYAML resolves the bare key `on:` to the boolean True.
    raw = workflow.get(True) if True in workflow else workflow.get("on")
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, list):
        return {str(k): None for k in raw}
    if isinstance(raw, str):
        return {raw: None}
    return {}


# ---------------------------------------------------------------- conditions
def check_action_pins(workflows: dict[Path, dict], f: Findings) -> None:
    """Conditions 3 and 4: one version per action, and that version pinned."""
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            f.fail("unparseable workflow", str(path), workflow["__error__"])
            continue
        text = path.read_text(encoding="utf-8")
        per_action: dict[str, set[str]] = {}
        for job_key, job in (workflow.get("jobs") or {}).items():
            for step in steps_of(job):
                uses = str(step.get("uses") or "")
                if not uses or uses.startswith(PIN_EXEMPT_PREFIXES):
                    continue
                action, _, ref = uses.partition("@")
                per_action.setdefault(action, set()).add(ref)
                if not SHA_RE.match(ref):
                    f.fail(
                        "unpinned action", f"{path}:{job_key}",
                        f"{uses} is not pinned to a 40-character commit SHA, so what "
                        f"runs in CI can change with no commit in this repository",
                    )
                    continue
                line = next((ln for ln in text.splitlines() if ref in ln), "")
                if not VERSION_COMMENT_RE.search(line):
                    f.fail(
                        "pin without a version comment", f"{path}:{job_key}",
                        f"{action}@{ref[:10]} has no `# vX.Y.Z` comment, so the "
                        f"pinned release is unreviewable without resolving the SHA",
                    )
        # Condition 3: the same action at two refs inside one workflow.
        for action, refs in sorted(per_action.items()):
            if len(refs) > 1:
                f.fail(
                    "split action version", str(path),
                    f"{action} is used at {len(refs)} different refs "
                    f"({', '.join(sorted(r[:10] for r in refs))}). Steps of one action "
                    f"must share a release -- codeql-action's non-init steps throw when "
                    f"they load a config generated by a different version",
                )


def check_permissions(workflows: dict[Path, dict], f: Findings) -> None:
    """Condition 5: least privilege, declared."""
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            continue
        top = workflow.get("permissions")
        jobs = workflow.get("jobs") or {}
        job_perms = {k: (v or {}).get("permissions")
                     for k, v in jobs.items() if isinstance(v, dict)}
        if top is None and not any(p is not None for p in job_perms.values()):
            f.fail(
                "missing permissions", str(path),
                "no `permissions:` at workflow or job level, so the job token "
                "inherits the repository default, which can be write-all",
            )
        for scope in (top, *job_perms.values()):
            if scope == "write-all":
                f.fail("permissions write-all", str(path),
                       "`permissions: write-all` grants every scope; name the scopes "
                       "the workflow actually needs")


def check_pull_request_target(workflows: dict[Path, dict], f: Findings) -> None:
    """Condition 6: the standard CI takeover."""
    head_refs = ("github.event.pull_request.head.sha",
                 "github.event.pull_request.head.ref",
                 "github.event.pull_request.merge_commit_sha")
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            continue
        if "pull_request_target" not in triggers_of(workflow):
            continue
        text = path.read_text(encoding="utf-8")
        hit = next((r for r in head_refs if r in text), None)
        if hit:
            f.fail(
                "pull_request_target checks out PR head", str(path),
                f"the workflow triggers on `pull_request_target` and references "
                f"`{hit}`, which runs the pull request's own code with a write token "
                f"and repository secrets",
            )


def check_gates_can_fail(workflows: dict[Path, dict], f: Findings) -> None:
    """Condition 7: a step that cannot fail is not a gate."""
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            continue
        for job_key, job in (workflow.get("jobs") or {}).items():
            if isinstance(job, dict) and job.get("continue-on-error") is True:
                f.fail("gate cannot fail", f"{path}:{job_key}",
                       "the whole job sets `continue-on-error: true`, so nothing it "
                       "runs can block a merge")
            for step in steps_of(job):
                if step.get("continue-on-error") is not True:
                    continue
                label = (str(step.get("name") or "") + " " + str(step.get("run") or "")).lower()
                if any(word in label for word in GATE_WORDS):
                    f.fail(
                        "gate cannot fail", f"{path}:{job_key}",
                        f"step {step.get('name') or step.get('uses') or '?'!r} looks "
                        f"like a gate but sets `continue-on-error: true`, which turns "
                        f"it into a notification",
                    )


def check_codeql_coherence(root: Path, workflows: dict[Path, dict], f: Findings) -> None:
    """Conditions 8 and 9: the CodeQL gate's own inputs."""
    codeql = next((w for p, w in workflows.items() if p.name.startswith("codeql")), None)
    if codeql is None or "__error__" in (codeql or {}):
        f.fail("codeql workflow missing", ".github/workflows/",
               "no parseable codeql workflow was found, so none of its controls "
               "can be audited")
        return
    analyze = (codeql.get("jobs") or {}).get("analyze") or {}
    include = (((analyze.get("strategy") or {}).get("matrix") or {}).get("include")
               if isinstance(analyze.get("strategy"), dict) else None)
    if not isinstance(include, list) or not include:
        f.fail("codeql matrix missing", "codeql.yml",
               "the analyze job has no matrix `include`, so the set of analysed "
               "languages cannot be checked")
        return

    sys.path.insert(0, str(root / "scripts" / "youtab"))
    try:
        from codeql_sarif_gate import LANGUAGES  # type: ignore
    except Exception as exc:  # noqa: BLE001
        f.fail("codeql gate unimportable", "codeql_sarif_gate.py", str(exc))
        return
    finally:
        sys.path.pop(0)

    baselines = root / "scripts" / "youtab" / "codeql_baselines"
    for leg in include:
        if not isinstance(leg, dict) or not leg.get("language"):
            f.fail("codeql matrix leg malformed", "codeql.yml", repr(leg))
            continue
        language = str(leg["language"])
        if language not in LANGUAGES:
            f.fail(
                "codeql language unknown to the gate", f"codeql.yml:{language}",
                "no entry in codeql_sarif_gate.LANGUAGES, so the comparator cannot "
                "read this leg's SARIF and rejects it as missing coverage metadata",
            )
        path = baselines / f"{language}.json"
        if not path.is_file():
            f.fail(
                "codeql leg without a baseline", f"codeql_baselines/{language}.json",
                "the gate step would fail on every run with a path error; generate it "
                "with regenerate_codeql_baseline.py from a complete run",
            )
            continue
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            f.fail("codeql baseline unreadable", str(path), str(exc))
            continue
        budget = document.get("severity_budget")
        if not isinstance(budget, dict) or not budget:
            f.fail(
                "baseline without a severity budget", str(path),
                "the severity ratchet lives in the baseline, so a baseline without a "
                "budget removes the control; rebuild it with "
                "regenerate_codeql_baseline.py",
            )
        for field in ("source_run", "source_head"):
            if not document.get(field):
                f.fail("baseline without provenance", str(path),
                       f"no `{field}`, so the baseline does not say which run it "
                       f"describes")
        for field in ("artifact_count", "query_count", "extracted_count"):
            if not isinstance(document.get(field), int) or document[field] <= 0:
                f.fail("baseline without coverage metadata", str(path),
                       f"`{field}` is {document.get(field)!r}; the gate requires it to "
                       f"be positive and will reject this baseline on every run")


def observed_contexts(repo: str, revisions: list[str]) -> set[str]:
    """Check-run names GitHub has actually reported on these commits.

    Deliberately NOT derived from the workflow files. Predicting a context
    name means reimplementing GitHub's matrix naming, and getting that wrong
    is the very bug this condition exists to catch -- a job with no ``name``
    gets its matrix values appended (``wake-word-backends (ubuntu-latest)``),
    a job with a constant ``name`` gets the whole matrix entry appended
    (``CodeQL analyze (python, none)``, which is how adding ``build-mode``
    orphaned three required checks), and a job whose name interpolates
    ``matrix.*`` gets exactly what it interpolates. A model of those rules
    that is subtly wrong produces false lockout reports, and a check that
    cries wolf gets deleted.

    So this asks the API what was reported, which is ground truth on both
    sides of the comparison.
    """
    import subprocess

    names: set[str] = set()
    for revision in revisions:
        try:
            out = subprocess.run(
                ["gh", "api", f"repos/{repo}/commits/{revision}/check-runs?per_page=100",
                 "--jq", ".check_runs[].name"],
                capture_output=True, text=True, timeout=90, check=True,
            ).stdout
        except Exception:  # noqa: BLE001 - a revision with no runs is not an error
            continue
        names |= {line.strip() for line in out.splitlines() if line.strip()}
    return names


def check_required_checks(root: Path, workflows: dict[Path, dict],
                          repo: str | None, f: Findings, require_remote: bool) -> None:
    """Conditions 1 and 2: the ruleset and the checks that actually run."""
    import os
    import subprocess

    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        message = ("no GH_TOKEN/GITHUB_TOKEN, so the branch ruleset could not be read. "
                   "Conditions 1 and 2 (required checks nothing produces, and gates "
                   "nothing requires) were NOT evaluated.")
        if require_remote:
            f.fail("ruleset unavailable", "rulesets", message)
        else:
            f.skip("required checks", message)
        return
    if not repo:
        f.skip("required checks", "no --repo given and it could not be inferred")
        return

    def api(path: str, *extra: str) -> str:
        # `path` may be empty (the repository itself); a trailing slash makes
        # `gh api` reject the route.
        route = f"repos/{repo}/{path}".rstrip("/")
        return subprocess.run(["gh", "api", route, *extra],
                              capture_output=True, text=True, timeout=90,
                              check=True).stdout

    try:
        ruleset_ids = api("rulesets", "--jq",
                          '.[] | select(.target=="branch") | .id').split()
        required: set[str] = set()
        for ruleset_id in ruleset_ids:
            body = json.loads(api(f"rulesets/{ruleset_id}"))
            for rule in body.get("rules") or []:
                if rule.get("type") != "required_status_checks":
                    continue
                params = rule.get("parameters") or {}
                for check in params.get("required_status_checks") or []:
                    if check.get("context"):
                        required.add(str(check["context"]))
        default_branch = json.loads(api("")).get("default_branch") or "main"
        recent = api(f"commits?sha={default_branch}&per_page=5", "--jq", ".[].sha").split()
    except Exception as exc:  # noqa: BLE001
        message = f"could not read the ruleset or recent commits for {repo}: {exc}"
        (f.fail("ruleset unavailable", "rulesets", message) if require_remote
         else f.skip("required checks", message))
        return

    if not required:
        f.fail("no required status checks", "rulesets",
               "no branch ruleset requires any status check, so every gate in this "
               "repository is advisory and nothing can block a merge")
        return

    head = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                          text=True, cwd=str(root)).stdout.strip()
    revisions = [r for r in ([head] + recent) if r]
    produced = observed_contexts(repo, revisions)
    if not produced:
        message = (f"no check runs found on {len(revisions)} recent revisions, so "
                   f"conditions 1 and 2 could not be evaluated against observed names")
        (f.fail("no observed check runs", "check-runs", message) if require_remote
         else f.skip("required checks", message))
        return

    # Condition 1: required, but nothing has ever reported it.
    for context in sorted(required - produced):
        f.fail(
            "required check nobody produces", context,
            f"the ruleset requires this context and no check run with that exact name "
            f"was reported on any of the last {len(revisions)} revisions, so every "
            f"pull request waits on it forever. GitHub matches required checks on the "
            f"reported JOB name -- a job with no `name` has its matrix values appended, "
            f"and a job with a constant `name` has the whole matrix entry appended",
        )

    # Condition 2: a CodeQL leg that reports but cannot block.
    codeql_reported = {c for c in produced if c.startswith("CodeQL analyze")}
    for context in sorted(codeql_reported - required):
        f.fail(
            "gate that cannot block", context,
            "this CodeQL leg reports on every pull request but is not a required "
            "check, so a failure in it does not prevent a merge",
        )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--json", dest="json_out", default=None)
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"),
                    help="owner/name, for reading the branch ruleset")
    ap.add_argument("--require-remote", action="store_true",
                    help="treat an unreadable ruleset as a FAILURE rather than a "
                         "skip. Use in CI, where the token exists and a skip would "
                         "mean the check silently stopped running.")
    args = ap.parse_args()

    root = args.root.resolve()
    f = Findings()
    workflows = load_workflows(root)
    if not workflows:
        f.fail("no workflows", ".github/workflows/", "nothing to audit")

    check_action_pins(workflows, f)
    check_permissions(workflows, f)
    check_pull_request_target(workflows, f)
    check_gates_can_fail(workflows, f)
    check_codeql_coherence(root, workflows, f)
    check_required_checks(root, workflows, args.repo, f, args.require_remote)

    for item in f.items:
        marker = "FAIL" if item["status"] == "fail" else "SKIP"
        where = f" [{item['where']}]" if item["where"] else ""
        print(f"{marker}: {item['condition']}{where}\n      {item['detail']}")

    if args.json_out:
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(
            json.dumps({"findings": f.items,
                        "failures": len(f.failures),
                        "skipped": len(f.skips),
                        "workflows": sorted(str(p.name) for p in workflows)},
                       indent=2, sort_keys=True),
            encoding="utf-8",
        )

    if f.failures:
        print(f"\nci-control: {len(f.failures)} failure(s), {len(f.skips)} skipped")
        return 1
    if f.skips:
        # Reported, never laundered into a pass -- AGENTS.md is explicit that a
        # blocked check must not become a PASS. The exit code stays 0 locally so
        # a developer without a token can still run the other conditions; CI
        # passes --require-remote, where a skip is a failure.
        print(f"\nci-control: PASS with {len(f.skips)} condition(s) SKIPPED "
              f"(not evaluated, not passed)")
        return 0
    print("\nci-control: PASS — all conditions evaluated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
