#!/usr/bin/env python3
"""Audit the controls that decide what "green" means.

Every other gate in this directory inspects the product. This one inspects
the gates: the workflows that run them, the pins that fix what code those
workflows execute, the ruleset that decides which of them can block a merge,
and the baselines that decide what counts as a finding. A defect here does
not show up as a failing check -- it shows up as a check that stops failing,
which is the one failure mode nothing else in the repository looks for.

Every condition below is one that has actually cost this repository a P1, and
the history is recorded against each so a later reader can judge whether the
rule still earns its place rather than deleting it as noise:

    1. required check nobody produces   A ruleset required the WORKFLOW name
                                        ``CodeQL no-new-findings gate`` and
                                        later ``CodeQL analyze (python, none)``
                                        after `build-mode` renamed the matrix
                                        contexts. GitHub matches required
                                        checks on JOB name, so every pull
                                        request blocked forever waiting on a
                                        status nothing emitted. Three times.

    2. gate that cannot block           ``CodeQL analyze (actions)``,
                                        ``(c-cpp)`` and ``(rust)`` ran and
                                        reported for days while being
                                        advisory, because nothing required
                                        them. A gate nobody requires is a log
                                        line.

    3. split action version             Dependabot bumped
                                        ``codeql-action/init`` to 4.38.2 and
                                        left ``analyze`` on 3.37.9. Since
                                        3.30.4 the non-init steps THROW when
                                        they load a config generated by a
                                        different version, so every run would
                                        have died at ``analyze`` with no SARIF
                                        -- a red gate whose cause is three
                                        steps away from its symptom.

    4. unpinned action                  A floating ``@v4`` silently follows
                                        upstream, so what runs in CI changes
                                        with no commit in this repository.

    5. missing permissions              A workflow with no ``permissions:``
                                        block inherits the token's default,
                                        which on older repository settings is
                                        write-all. The CodeQL workflow needs
                                        ``security-events: write`` and nothing
                                        else.

    6. pull_request_target + PR head    Checking out the pull request's head
                                        under ``pull_request_target`` runs
                                        untrusted code with a write token and
                                        secrets. This is the standard CI
                                        takeover, and no scanner here looked
                                        for it.

    7. gate that cannot fail            ``continue-on-error: true`` on a step
                                        whose job is to fail turns it into a
                                        notification.

    8. baseline without a budget        The severity ratchet lives in the
                                        baseline. A baseline built before it
                                        existed, or regenerated with an older
                                        script, silently removes the control.

    9. CodeQL leg with no baseline      A matrix language with no committed
                                        baseline fails its gate step on every
                                        run with a path error, and the usual
                                        response is to drop the gate.

Each condition fails CLOSED. Where a condition cannot be evaluated -- the
ruleset needs an API token -- it is reported as SKIPPED and never as PASS,
and ``--require-remote`` turns a skip into a failure for CI, where the token
is present and a skip would mean the check silently stopped running.

Usage::

    python scripts/youtab/ci_control_gate.py --root . --json evidence.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

SHA_RE = re.compile(r"^[0-9a-f]{40}$")
VERSION_COMMENT_RE = re.compile(r"#\s*v?\d+(\.\d+)*")

#: Actions from GitHub's own namespaces still get pinned -- the 2025
#: tj-actions/changed-files compromise was a widely trusted third-party action
#: whose tags were rewritten, and nothing about the owner changes the argument.
#:
#: Only LOCAL actions are exempt: this repository's own content, already
#: covered by whatever protects the default branch, with its manifest audited
#: directly (see `load_composite_actions`).
#:
#: Two spellings, both documented:
#:   `./path/to/dir`      a path in the checked-out workspace
#:   `$/path/to/action`   the self repository at the RUNNING commit, which
#:                        GitHub now prefers ("For most cases, use the `$/`
#:                        syntax shown above instead") and which must NOT
#:                        carry an `@{ref}` suffix
#:
#: Missing `$/` was not a gap in coverage but a false FAILURE: the reference
#: has no ref to be a SHA, so the pin check rejected a valid workflow for
#: "not pinned to a 40-character commit SHA" and would have blocked anyone
#: adopting the preferred syntax.
#:
#: `docker://` used to be exempt too, which skipped the reference before any
#: validation -- so `docker://image:latest` let upstream change the executed
#: image with no commit here while the audit stayed green. Container actions
#: are checked by `_docker_pin_problem` instead.
PIN_EXEMPT_PREFIXES: tuple[str, ...] = ("./", "$/")

#: A container action is immutable only when it names a digest.
DOCKER_DIGEST_RE = re.compile(r"@sha256:[0-9a-f]{64}$")

#: A step is treated as a gate when its name or command says so. Used only to
#: decide whether `continue-on-error` is suspicious, so a false positive costs
#: a comment and a false negative costs a silent gate.
GATE_WORDS = ("gate", "test", "lint", "typecheck", "type-check", "audit",
              "scan", "verify", "check")


class Findings:
    """Collects findings so every condition is evaluated before exiting."""

    def __init__(self) -> None:
        self.items: list[dict[str, Any]] = []

    def fail(self, condition: str, where: str, detail: str) -> None:
        self.items.append({"status": "fail", "condition": condition,
                           "where": where, "detail": detail})

    def skip(self, condition: str, detail: str) -> None:
        self.items.append({"status": "skip", "condition": condition,
                           "where": "", "detail": detail})

    @property
    def failures(self) -> list[dict[str, Any]]:
        return [i for i in self.items if i["status"] == "fail"]

    @property
    def skips(self) -> list[dict[str, Any]]:
        return [i for i in self.items if i["status"] == "skip"]


def _docker_pin_problem(uses: str) -> str | None:
    """Why a `docker://` reference is not immutable, or None if it is.

    GitHub supports tagged images in `uses:` and recommends verifying their
    integrity; a tag is mutable, so the only reference that pins what runs is
    a digest.
    """
    if not uses.startswith("docker://"):
        return None
    if DOCKER_DIGEST_RE.search(uses):
        return None
    return (
        f"{uses} is a container action pinned by tag, not by digest, so "
        f"upstream can change the image that runs with no commit in this "
        f"repository. Use docker://image@sha256:<64 hex>."
    )


def load_composite_actions(root: Path) -> dict[Path, dict]:
    """This repository's own composite-action manifests, as pseudo-workflows.

    A composite action invokes external actions through `runs.steps[*].uses`,
    and those run with the CALLING workflow's privileges -- so a manifest that
    switches a dependency to `@main` is exactly as dangerous as a workflow
    doing it, and `load_workflows` never looked at one. This repository has
    three such dependencies today (`actions/create-github-app-token`,
    `DeterminateSystems/nix-installer-action`, `cachix/cachix-action`).

    Shaped as `{"jobs": {"<composite>": {"steps": ...}}}` so the pin audit
    reads them unchanged. Deliberately NOT fed to the permissions,
    `pull_request_target` or continue-on-error conditions: a composite action
    has no `permissions`, no triggers and no job-level settings, so those
    conditions do not apply and reporting them would be noise.
    """
    import yaml

    #: Directories that never hold this repository's own actions and would
    #: cost real time to walk.
    skip = {".git", "node_modules", ".venv", "venv", "__pycache__", ".mypy_cache",
            ".pytest_cache", "dist", "build", ".youtab", "target", "site-packages"}

    def manifests() -> list[Path]:
        """Every `action.y{a,}ml` in the repository, at any depth.

        A single-level glob over `.github/actions/*/` missed a composite in a
        nested directory such as `.github/actions/team/deploy/`, or one kept
        anywhere else -- GitHub permits same-repository composites in any
        subfolder. Meanwhile the workflow-side `./` or `$/` reference to it is
        exempt from the pin check by design, so an `@main` dependency inside
        an unscanned manifest was invisible to the required gate from both
        directions at once.
        """
        found: list[Path] = []
        for candidate in root.rglob("action.y*ml"):
            if any(part in skip for part in candidate.parts):
                continue
            if candidate.suffix not in (".yml", ".yaml"):
                continue
            found.append(candidate)
        return sorted(found)

    out: dict[Path, dict] = {}
    for path in manifests():
        try:
            loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001 - an unreadable manifest is a failure
            out[path] = {"__error__": str(exc)}
            continue
        if not isinstance(loaded, dict):
            out[path] = {"__error__": "not a mapping"}
            continue
        steps = ((loaded.get("runs") or {}).get("steps")
                 if isinstance(loaded.get("runs"), dict) else None)
        out[path] = {"jobs": {"<composite>": {"steps": steps or []}}}
    return out


def load_workflows(root: Path) -> dict[Path, dict]:
    import yaml

    out: dict[Path, dict] = {}
    for path in sorted((root / ".github" / "workflows").glob("*.y*ml")):
        try:
            loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001 - an unparseable workflow is a failure
            out[path] = {"__error__": str(exc)}
            continue
        out[path] = loaded if isinstance(loaded, dict) else {"__error__": "not a mapping"}
    return out


def steps_of(job: Any) -> list[dict]:
    if not isinstance(job, dict):
        return []
    return [s for s in (job.get("steps") or []) if isinstance(s, dict)]


def triggers_of(workflow: dict) -> dict:
    # PyYAML resolves the bare key `on:` to the boolean True.
    raw = workflow.get(True) if True in workflow else workflow.get("on")
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, list):
        return {str(k): None for k in raw}
    if isinstance(raw, str):
        return {raw: None}
    return {}


# ---------------------------------------------------------------- conditions
def check_action_pins(workflows: dict[Path, dict], f: Findings) -> None:
    """Conditions 3 and 4: one version per action, and that version pinned."""
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            f.fail("unparseable workflow", str(path), workflow["__error__"])
            continue
        text = path.read_text(encoding="utf-8")
        per_action: dict[str, set[str]] = {}
        for job_key, job in (workflow.get("jobs") or {}).items():
            # Job-level `uses:` is a REUSABLE WORKFLOW call
            # (`jobs.<id>.uses: owner/repo/.github/workflows/ci.yml@ref`), not
            # a step, so iterating `job.steps` alone omitted it entirely and a
            # mutable `@main` external workflow passed the audit. It runs with
            # this repository's token, so it needs the same pin discipline.
            job_uses = str((job or {}).get("uses") or "") if isinstance(job, dict) else ""
            candidates = [("<job>", job_uses)] if job_uses else []
            candidates += [("step", str(step.get("uses") or "")) for step in steps_of(job)]
            for where, uses in candidates:
                if not uses or uses.startswith(PIN_EXEMPT_PREFIXES):
                    continue
                docker_problem = _docker_pin_problem(uses)
                if docker_problem is not None:
                    f.fail("unpinned container action", f"{path}:{job_key}",
                           docker_problem)
                    continue
                if uses.startswith("docker://"):
                    # Digest-pinned: immutable, and not an action repository,
                    # so it takes no part in the split-version grouping below.
                    continue
                action, _, ref = uses.partition("@")
                # Keyed by REPOSITORY, not by the full action path. Keying on
                # the path put `github/codeql-action/init` and
                # `github/codeql-action/analyze` in separate buckets with one
                # ref each, so the split-version condition passed on exactly
                # the shape it exists to catch -- dependabot's #74. Sub-actions
                # of one repository share a release, and codeql-action's
                # non-init steps throw when they load a config generated by a
                # different version.
                repo_key = "/".join(action.split("/")[:2])
                per_action.setdefault(repo_key, set()).add(ref)
                if not SHA_RE.match(ref):
                    f.fail(
                        "unpinned action", f"{path}:{job_key}",
                        f"{uses} ({where}) is not pinned to a 40-character commit SHA, "
                        f"so what runs in CI can change with no commit in this repository",
                    )
                    continue
                line = next((ln for ln in text.splitlines() if ref in ln), "")
                if not VERSION_COMMENT_RE.search(line):
                    f.fail(
                        "pin without a version comment", f"{path}:{job_key}",
                        f"{action}@{ref[:10]} has no `# vX.Y.Z` comment, so the "
                        f"pinned release is unreviewable without resolving the SHA",
                    )
        # Condition 3: the same action at two refs inside one workflow.
        for action, refs in sorted(per_action.items()):
            if len(refs) > 1:
                f.fail(
                    "split action version", str(path),
                    f"{action} is used at {len(refs)} different refs "
                    f"({', '.join(sorted(r[:10] for r in refs))}). Steps of one action "
                    f"must share a release -- codeql-action's non-init steps throw when "
                    f"they load a config generated by a different version",
                )


def check_permissions(workflows: dict[Path, dict], f: Findings) -> None:
    """Condition 5: least privilege, declared."""
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            continue
        top = workflow.get("permissions")
        jobs = workflow.get("jobs") or {}
        job_perms = {k: (v or {}).get("permissions")
                     for k, v in jobs.items() if isinstance(v, dict)}
        if top is None:
            # PER JOB, not `any(...)`. Job-level permissions configure jobs
            # independently, so a workflow with no top-level block and one job
            # that declares its own leaves every OTHER job on the repository
            # default -- which the `any(...)` form reported as protected.
            for job_key, scopes in sorted(job_perms.items()):
                if scopes is None:
                    f.fail(
                        "missing permissions", f"{path}:{job_key}",
                        "no `permissions:` at workflow level and none on this job, so "
                        "its token inherits the repository default, which can be "
                        "write-all. A sibling job's block does not cover it.",
                    )
            if not job_perms:
                f.fail(
                    "missing permissions", str(path),
                    "no `permissions:` at workflow level and no jobs to carry one",
                )
        for scope in (top, *job_perms.values()):
            if scope == "write-all":
                f.fail("permissions write-all", str(path),
                       "`permissions: write-all` grants every scope; name the scopes "
                       "the workflow actually needs")


#: Expressions that resolve to the BASE of a pull request, which is the
#: repository's own trusted code and therefore safe to check out under
#: `pull_request_target`.
SAFE_PR_TARGET_REFS = ("github.event.pull_request.base.sha",
                       "github.event.pull_request.base.ref",
                       "github.base_ref",
                       "github.sha",
                       "github.ref")


def check_pull_request_target(workflows: dict[Path, dict], f: Findings) -> None:
    """Condition 6: the standard CI takeover.

    Allowlists the SAFE shapes rather than enumerating dangerous ones. The
    first version listed three spellings of the pull request's head and
    missed `github.head_ref` -- the standard alias, and the one the classic
    takeover actually uses -- which is the trouble with a denylist of
    expressions: the next spelling is always missing. GitHub keeps several,
    and `github.head_ref` is populated on exactly these events.

    So a checkout under `pull_request_target` is reported unless its `ref` is
    one of three safe things: absent (the action checks out the BASE by
    default, which is the whole reason `pull_request_target` is usable at
    all), a literal with no expression in it, or an expression naming the
    base.
    """
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            continue
        if "pull_request_target" not in triggers_of(workflow):
            continue

        for job_key, job in (workflow.get("jobs") or {}).items():
            for step in steps_of(job):
                uses = str(step.get("uses") or "")
                if not uses.startswith("actions/checkout"):
                    continue
                ref = str(((step.get("with") or {}).get("ref")) or "")
                if not ref:
                    continue                      # defaults to the base
                if "${{" not in ref:
                    continue                      # a literal branch or tag
                if any(safe in ref for safe in SAFE_PR_TARGET_REFS):
                    continue
                f.fail(
                    "pull_request_target checks out PR head", f"{path}:{job_key}",
                    f"the workflow triggers on `pull_request_target` and checks out "
                    f"`ref: {ref}`, which is not a base reference, so it runs the "
                    f"pull request's own code with a write token and repository "
                    f"secrets. Omit `ref` to take the base, or name "
                    f"`github.event.pull_request.base.sha` explicitly.",
                )

        # A checkout is the usual vehicle but not the only one: a `run:` step
        # can fetch and check out the head itself. This catches the head
        # expressions anywhere else in the file, including `github.head_ref`,
        # which the earlier list omitted.
        text = path.read_text(encoding="utf-8")
        elsewhere = ("github.head_ref",
                     "github.event.pull_request.head.sha",
                     "github.event.pull_request.head.ref",
                     "github.event.pull_request.merge_commit_sha")
        hit = next((r for r in elsewhere if r in text), None)
        if hit and not any(
            i["condition"] == "pull_request_target checks out PR head"
            and i["where"].startswith(str(path))
            for i in f.items
        ):
            f.fail(
                "pull_request_target references PR head", str(path),
                f"the workflow triggers on `pull_request_target` and references "
                f"`{hit}` outside a checkout step; anything that materialises the "
                f"pull request's own code here runs it with a write token and "
                f"repository secrets",
            )


def check_gates_can_fail(workflows: dict[Path, dict], f: Findings) -> None:
    """Condition 7: a step that cannot fail is not a gate."""
    for path, workflow in workflows.items():
        if "__error__" in workflow:
            continue
        for job_key, job in (workflow.get("jobs") or {}).items():
            if isinstance(job, dict) and job.get("continue-on-error") is True:
                f.fail("gate cannot fail", f"{path}:{job_key}",
                       "the whole job sets `continue-on-error: true`, so nothing it "
                       "runs can block a merge")
            for step in steps_of(job):
                if step.get("continue-on-error") is not True:
                    continue
                label = (str(step.get("name") or "") + " " + str(step.get("run") or "")).lower()
                if any(word in label for word in GATE_WORDS):
                    f.fail(
                        "gate cannot fail", f"{path}:{job_key}",
                        f"step {step.get('name') or step.get('uses') or '?'!r} looks "
                        f"like a gate but sets `continue-on-error: true`, which turns "
                        f"it into a notification",
                    )


def check_codeql_coherence(root: Path, workflows: dict[Path, dict], f: Findings) -> None:
    """Conditions 8 and 9: the CodeQL gate's own inputs."""
    codeql = next((w for p, w in workflows.items() if p.name.startswith("codeql")), None)
    if codeql is None or "__error__" in (codeql or {}):
        f.fail("codeql workflow missing", ".github/workflows/",
               "no parseable codeql workflow was found, so none of its controls "
               "can be audited")
        return
    analyze = (codeql.get("jobs") or {}).get("analyze") or {}
    include = (((analyze.get("strategy") or {}).get("matrix") or {}).get("include")
               if isinstance(analyze.get("strategy"), dict) else None)
    if not isinstance(include, list) or not include:
        f.fail("codeql matrix missing", "codeql.yml",
               "the analyze job has no matrix `include`, so the set of analysed "
               "languages cannot be checked")
        return

    sys.path.insert(0, str(root / "scripts" / "youtab"))
    try:
        from codeql_sarif_gate import LANGUAGES  # type: ignore
    except Exception as exc:  # noqa: BLE001
        f.fail("codeql gate unimportable", "codeql_sarif_gate.py", str(exc))
        return
    finally:
        sys.path.pop(0)

    baselines = root / "scripts" / "youtab" / "codeql_baselines"
    for leg in include:
        if not isinstance(leg, dict) or not leg.get("language"):
            f.fail("codeql matrix leg malformed", "codeql.yml", repr(leg))
            continue
        language = str(leg["language"])
        if language not in LANGUAGES:
            f.fail(
                "codeql language unknown to the gate", f"codeql.yml:{language}",
                "no entry in codeql_sarif_gate.LANGUAGES, so the comparator cannot "
                "read this leg's SARIF and rejects it as missing coverage metadata",
            )
        path = baselines / f"{language}.json"
        if not path.is_file():
            f.fail(
                "codeql leg without a baseline", f"codeql_baselines/{language}.json",
                "the gate step would fail on every run with a path error; generate it "
                "with regenerate_codeql_baseline.py from a complete run",
            )
            continue
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            f.fail("codeql baseline unreadable", str(path), str(exc))
            continue
        budget = document.get("severity_budget")
        if not isinstance(budget, dict) or not budget:
            f.fail(
                "baseline without a severity budget", str(path),
                "the severity ratchet lives in the baseline, so a baseline without a "
                "budget removes the control; rebuild it with "
                "regenerate_codeql_baseline.py",
            )
        for field in ("source_run", "source_head"):
            if not document.get(field):
                f.fail("baseline without provenance", str(path),
                       f"no `{field}`, so the baseline does not say which run it "
                       f"describes")
        for field in ("artifact_count", "query_count", "extracted_count"):
            if not isinstance(document.get(field), int) or document[field] <= 0:
                f.fail("baseline without coverage metadata", str(path),
                       f"`{field}` is {document.get(field)!r}; the gate requires it to "
                       f"be positive and will reject this baseline on every run")


def ruleset_protects(body: dict, default_branch: str) -> bool:
    """Whether this branch ruleset is active AND covers the default branch.

    `conditions.ref_name` carries `include` and `exclude` lists of refs, with
    two special tokens: `~ALL` for every branch and `~DEFAULT_BRANCH` for the
    repository default. Patterns are fnmatch-style, e.g.
    `refs/heads/release/*`. This repository's own ruleset reads
    `{"include": ["refs/heads/main"], "exclude": []}`.

    A ruleset that does not protect the default branch must not contribute
    required contexts, because they are compared against the default
    branch's check runs -- a `release/*`-only context would read as "required
    but nobody produces it" and fail the required job on every pull request.
    """
    import fnmatch

    if body.get("enforcement") != "active":
        return False
    ref_name = ((body.get("conditions") or {}).get("ref_name") or {})
    include = ref_name.get("include") or []
    exclude = ref_name.get("exclude") or []
    target = f"refs/heads/{default_branch}"

    def matches(patterns: list) -> bool:
        for pattern in patterns:
            text = str(pattern)
            if text == "~ALL":
                return True
            if text == "~DEFAULT_BRANCH":
                return True
            if fnmatch.fnmatch(target, text):
                return True
        return False

    if not include:
        # No include list at all protects nothing in particular; treat it as
        # not covering the default branch rather than guessing it covers
        # everything.
        return False
    return matches(include) and not matches(exclude)


def _pull_request_head_sha() -> str | None:
    """The head SHA of the pull request this run is auditing, if any.

    Read from the event payload rather than guessed from `GITHUB_SHA`, which
    on a `pull_request` event is the merge commit. Returns None outside a
    pull-request run, where the default-branch tip is the only relevant
    state.
    """
    if os.environ.get("GITHUB_EVENT_NAME") != "pull_request":
        return None
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        return None
    try:
        payload = json.loads(Path(event_path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    head = ((payload.get("pull_request") or {}).get("head") or {}).get("sha")
    return str(head) if head else None


def observed_contexts(repo: str, revision: str) -> set[str]:
    """Check-run names GitHub has actually reported on these commits.

    Deliberately NOT derived from the workflow files. Predicting a context
    name means reimplementing GitHub's matrix naming, and getting that wrong
    is the very bug this condition exists to catch -- a job with no ``name``
    gets its matrix values appended (``wake-word-backends (ubuntu-latest)``),
    a job with a constant ``name`` gets the whole matrix entry appended
    (``CodeQL analyze (python, none)``, which is how adding ``build-mode``
    orphaned three required checks), and a job whose name interpolates
    ``matrix.*`` gets exactly what it interpolates. A model of those rules
    that is subtly wrong produces false lockout reports, and a check that
    cries wolf gets deleted.

    So this asks the API what was reported, which is ground truth on both
    sides of the comparison.

    ONE revision, never a union of several. The first version read five recent
    default-branch commits and unioned them, which defeats the condition: a
    renamed or removed context is still present in history, so
    ``required - produced`` came out empty exactly while branch protection
    waited forever for a context the current revision cannot produce.
    Availability is a property of the current revision.
    """
    try:
        out = subprocess.run(
            ["gh", "api", f"repos/{repo}/commits/{revision}/check-runs?per_page=100",
             "--jq", ".check_runs[].name"],
            capture_output=True, text=True, timeout=90, check=True,
        ).stdout
    except Exception:  # noqa: BLE001 - reported by the caller as unevaluable
        return set()
    # Presence, not conclusion: a check still `in_progress` has registered its
    # name, which is all availability means here.
    return {line.strip() for line in out.splitlines() if line.strip()}


def check_required_checks(root: Path, workflows: dict[Path, dict],
                          repo: str | None, f: Findings, require_remote: bool) -> None:
    """Conditions 1 and 2: the ruleset and the checks that actually run."""
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        message = ("no GH_TOKEN/GITHUB_TOKEN, so the branch ruleset could not be read. "
                   "Conditions 1 and 2 (required checks nothing produces, and gates "
                   "nothing requires) were NOT evaluated.")
        if require_remote:
            f.fail("ruleset unavailable", "rulesets", message)
        else:
            f.skip("required checks", message)
        return
    if not repo:
        message = ("no --repo given and GITHUB_REPOSITORY is unset, so the ruleset "
                   "could not be identified. Conditions 1 and 2 were NOT evaluated.")
        if require_remote:
            # Strict mode exists so a condition cannot quietly stop running.
            # Skipping here made the explicitly-strict audit non-enforcing on
            # an authenticated local or publication run, which is the same
            # silent downgrade the flag was added to prevent.
            f.fail("repository unknown", "rulesets", message)
        else:
            f.skip("required checks", message)
        return

    def api(path: str, *extra: str) -> str:
        # `path` may be empty (the repository itself); a trailing slash makes
        # `gh api` reject the route.
        route = f"repos/{repo}/{path}".rstrip("/")
        return subprocess.run(["gh", "api", route, *extra],
                              capture_output=True, text=True, timeout=90,
                              check=True).stdout

    try:
        # The default branch first: it decides which rulesets are even
        # relevant, so it cannot be resolved after them.
        default_branch = json.loads(api("")).get("default_branch") or "main"
        ruleset_ids = api("rulesets", "--jq",
                          '.[] | select(.target=="branch") | .id').split()
        required: set[str] = set()
        skipped_rulesets: list[str] = []
        for ruleset_id in ruleset_ids:
            body = json.loads(api(f"rulesets/{ruleset_id}"))
            # Only ACTIVE rulesets that actually protect the default branch.
            # Unioning every branch ruleset meant a disabled one, or one scoped
            # to `release/*`, contributed required contexts that the main tip
            # never produces -- reported as "required check nobody produces"
            # and failing the required python-security job on every pull
            # request. A false lockout report from the lockout detector.
            if not ruleset_protects(body, default_branch):
                skipped_rulesets.append(
                    f"{body.get('name') or ruleset_id} "
                    f"(enforcement={body.get('enforcement')})"
                )
                continue
            for rule in body.get("rules") or []:
                if rule.get("type") != "required_status_checks":
                    continue
                params = rule.get("parameters") or {}
                for check in params.get("required_status_checks") or []:
                    if check.get("context"):
                        required.add(str(check["context"]))
        if skipped_rulesets:
            print(f"NOTE: ignoring {len(skipped_rulesets)} branch ruleset(s) that do "
                  f"not protect {default_branch}: {', '.join(skipped_rulesets)}")
        # Short-circuit before resolving the tip: if nothing is required there
        # is no availability question to answer, and this is itself the
        # finding.
        if not required:
            f.fail("no required status checks", "rulesets",
                   "no branch ruleset requires any status check, so every gate in "
                   "this repository is advisory and nothing can block a merge")
            return
        tip = api(f"commits?sha={default_branch}&per_page=1", "--jq", ".[0].sha").strip()
    except Exception as exc:  # noqa: BLE001
        # Distinguish "no permission" from "could not reach it", because the
        # remedies are different and a bare failure here is unactionable.
        # Reading rulesets is not one of the scopes a workflow `permissions:`
        # block can grant, so the default GITHUB_TOKEN may be refused; that
        # needs a token with repository administration read, supplied as a
        # secret, not a retry.
        text = str(exc)
        scope = ("403" in text or "404" in text or "Not Found" in text
                 or "Resource not accessible" in text)
        message = (
            f"could not read the ruleset for {repo}: {exc}"
            + ("\n      The token cannot read rulesets. `permissions:` in a workflow "
               "has no `administration` scope, so the default GITHUB_TOKEN is refused "
               "here -- supply a token with repository administration:read as a secret, "
               "or run this gate without --require-remote and audit the ruleset by hand."
               if scope else "")
        )
        (f.fail("ruleset unavailable", "rulesets", message) if require_remote
         else f.skip("required checks", message))
        return

    # The default-branch TIP, not this working tree's HEAD. The question is
    # "can the branch this ruleset protects produce the contexts it requires",
    # and the tip is the revision where every job has finished and registered
    # its name. A local HEAD may be an unpushed commit with no runs at all.
    if not tip:
        message = f"could not resolve the tip of {default_branch}"
        (f.fail("no observed check runs", "check-runs", message) if require_remote
         else f.skip("required checks", message))
        return
    # The default-branch tip AND, on a pull request, the pull request's own
    # head.
    #
    # The tip alone deadlocks the change that introduces a context: this audit
    # runs inside `python-security` on `pull_request`, so when this very pull
    # request adds the `actions`, `c-cpp` and `rust` CodeQL legs and they are
    # made required, the tip cannot possibly have reported them yet and
    # `required - produced` fails forever on the only pull request that could
    # fix it.
    #
    # This is NOT the history union that was removed earlier. That unioned
    # five PAST revisions of main, so a context that had been renamed away
    # still looked produced. These two are both CURRENT states: what main
    # does now, and what the change under review proposes. A context that
    # neither produces is genuinely unproducible, which is the condition.
    # ONE revision, and on a pull request it is the pull request's own head.
    #
    # Unioning it with main's tip looked safer and was not: a pull request
    # that REMOVES or renames a required job is blocked -- its own run cannot
    # emit that context -- while main's tip still reports the old name, so
    # `required - produced` came out empty and the audit passed on a pull
    # request that cannot merge. That is the same masking as the historical
    # union, reached through a different door.
    #
    # The question this condition answers is "can the revision under review
    # produce what is required", so the revision under review is the only one
    # that can answer it. Outside a pull request there is no such revision and
    # the default-branch tip is the subject.
    #
    # Timing is the one cost: the gate runs inside `python-security`, so a
    # sibling job's context must already be registered. It is -- GitHub
    # creates a check run when a job is QUEUED, and `observed_contexts` keys
    # on presence rather than conclusion, so an `in_progress` leg counts.
    pr_head = _pull_request_head_sha()
    revisions = [pr_head] if pr_head else [tip]
    produced: set[str] = set()
    for revision in revisions:
        produced |= observed_contexts(repo, revision)
    if not produced:
        message = (f"no check runs on {default_branch} tip {tip[:9]}, so conditions 1 "
                   f"and 2 could not be evaluated against observed names")
        (f.fail("no observed check runs", "check-runs", message) if require_remote
         else f.skip("required checks", message))
        return

    # Condition 1: required, but nothing has ever reported it.
    for context in sorted(required - produced):
        f.fail(
            "required check nobody produces", context,
            f"the ruleset requires this context and no check run with that exact name "
            f"was reported on "
            f"{', '.join(r[:9] for r in revisions)} "
            + ("(this pull request's head)" if pr_head
               else f"({default_branch} tip)")
            + f", so every pull request waits on it forever. GitHub matches required "
            f"checks on the reported JOB name -- a job with no `name` has its matrix "
            f"values appended, and a job with a constant `name` has the whole matrix "
            f"entry appended",
        )

    # Condition 2: a CodeQL leg that reports but cannot block.
    codeql_reported = {c for c in produced if c.startswith("CodeQL analyze")}
    for context in sorted(codeql_reported - required):
        f.fail(
            "gate that cannot block", context,
            "this CodeQL leg reports on every pull request but is not a required "
            "check, so a failure in it does not prevent a merge",
        )


def remote_required_by_default() -> bool:
    """Whether an unreadable ruleset should FAIL rather than skip.

    True when a token is available, because then "could not read the ruleset"
    is a real problem rather than a missing capability -- and a skip there
    would mean the condition silently stopped running, which AGENTS.md
    forbids converting into a PASS.

    False on a workstation with no token, so a developer still gets the other
    seven conditions instead of a failure they cannot act on.
    """
    return bool(os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--json", dest="json_out", default=None)
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"),
                    help="owner/name, for reading the branch ruleset")
    ap.add_argument("--require-remote", dest="require_remote",
                    action="store_true", default=None,
                    help="treat an unreadable ruleset as a FAILURE rather than a skip")
    ap.add_argument("--no-require-remote", dest="require_remote",
                    action="store_false",
                    help="never fail on an unreadable ruleset, even with a token")
    args = ap.parse_args()

    root = args.root.resolve()
    # Strictness follows CAPABILITY by default, decided here rather than by the
    # caller. The wrapper used to pass the flag conditionally from shell, which
    # is a second place to drift from -- and the hole this closes came from
    # exactly that kind of split: the CI step exported only
    # YOUTAB_AGENT_PYTHON, `gh` needs GH_TOKEN explicitly inside a workflow, so
    # the two ruleset conditions were skipped on every CI run while the wrapper
    # printed PASS. Now exporting the token is the only thing CI has to do, and
    # both flags remain for forcing either way.
    require_remote = (
        remote_required_by_default() if args.require_remote is None
        else args.require_remote
    )
    f = Findings()
    workflows = load_workflows(root)
    if not workflows:
        f.fail("no workflows", ".github/workflows/", "nothing to audit")

    check_action_pins(workflows, f)
    # Composite manifests get the PIN conditions only -- see
    # `load_composite_actions` for why the others do not apply.
    composites = load_composite_actions(root)
    if composites:
        check_action_pins(composites, f)
    check_permissions(workflows, f)
    check_pull_request_target(workflows, f)
    check_gates_can_fail(workflows, f)
    check_codeql_coherence(root, workflows, f)
    check_required_checks(root, workflows, args.repo, f, require_remote)

    for item in f.items:
        marker = "FAIL" if item["status"] == "fail" else "SKIP"
        where = f" [{item['where']}]" if item["where"] else ""
        print(f"{marker}: {item['condition']}{where}\n      {item['detail']}")

    if args.json_out:
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(
            json.dumps({"findings": f.items,
                        "failures": len(f.failures),
                        "skipped": len(f.skips),
                        "workflows": sorted(str(p.name) for p in workflows)},
                       indent=2, sort_keys=True),
            encoding="utf-8",
        )

    if f.failures:
        print(f"\nci-control: {len(f.failures)} failure(s), {len(f.skips)} skipped")
        return 1
    if f.skips:
        # Reported, never laundered into a pass -- AGENTS.md is explicit that a
        # blocked check must not become a PASS. The exit code stays 0 locally so
        # a developer without a token can still run the other conditions; CI
        # passes --require-remote, where a skip is a failure.
        print(f"\nci-control: PASS with {len(f.skips)} condition(s) SKIPPED "
              f"(not evaluated, not passed)")
        return 0
    print("\nci-control: PASS — all conditions evaluated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
