"""Every condition in the CI-control gate must actually fire.

A gate that audits other gates is only worth having if each of its own
conditions is known to detect the thing it names. Each test below builds the
defect as a real workflow or baseline on disk and asserts the condition
reports it -- and, as importantly, that the healthy shape does not trip it,
because a control that cries wolf is deleted rather than fixed.

The two conditions that need the GitHub API (a required check nobody
produces, and a gate nothing requires) are covered for their SKIP behaviour
only: they must report as skipped rather than passing, which is what
AGENTS.md requires of a blocked check.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
GATE_PATH = REPO_ROOT / "scripts" / "youtab" / "ci_control_gate.py"


@pytest.fixture(scope="module")
def gate():
    pytest.importorskip("yaml")
    assert GATE_PATH.is_file(), f"missing {GATE_PATH}"
    spec = importlib.util.spec_from_file_location("ci_control_gate", GATE_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(GATE_PATH.parent))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.remove(str(GATE_PATH.parent))
    return module


HEALTHY = """\
name: ci
on:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: test
        run: pytest -q
"""


def write_workflow(root: Path, name: str, body: str) -> Path:
    directory = root / ".github" / "workflows"
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / name
    path.write_text(body, encoding="utf-8")
    return path


def conditions(gate, root: Path, *, checks) -> list[str]:
    """Run one or more conditions over `root` and return the failed names."""
    findings = gate.Findings()
    workflows = gate.load_workflows(root)
    for check in checks:
        if check is gate.check_codeql_coherence:
            check(root, workflows, findings)
        else:
            check(workflows, findings)
    return [item["condition"] for item in findings.failures]


def test_a_healthy_workflow_trips_nothing(gate, tmp_path):
    """The false-positive guard. Without this the rest is unfalsifiable."""
    write_workflow(tmp_path, "ci.yml", HEALTHY)
    failed = conditions(gate, tmp_path, checks=[
        gate.check_action_pins,
        gate.check_permissions,
        gate.check_pull_request_target,
        gate.check_gates_can_fail,
    ])
    assert failed == [], failed


def test_an_unpinned_action_is_reported(gate, tmp_path):
    """A floating tag changes what runs in CI with no commit here."""
    write_workflow(tmp_path, "ci.yml",
                   HEALTHY.replace("actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1",
                                   "actions/checkout@v4"))
    assert "unpinned action" in conditions(gate, tmp_path,
                                          checks=[gate.check_action_pins])


def test_a_pin_without_a_version_comment_is_reported(gate, tmp_path):
    """A bare 40-character SHA is unreviewable without resolving it."""
    write_workflow(tmp_path, "ci.yml", HEALTHY.replace(" # v7.0.1", ""))
    assert "pin without a version comment" in conditions(
        gate, tmp_path, checks=[gate.check_action_pins])


def test_two_refs_for_one_codeql_subaction_are_reported(gate, tmp_path):
    """dependabot's #74 shape, which the first version of this test blessed.

    It bumped `github/codeql-action/init` to 4.38.2 and left `analyze` on
    3.37.9. Since 3.30.4 the non-init steps THROW when they load a config
    generated by a different version, so every run dies at `analyze` with no
    SARIF.

    The first version of this test asserted that was FINE, because the gate
    keyed on the full action path and put `init` and `analyze` in separate
    buckets with one ref each. Keying on the REPOSITORY is what makes the
    condition detect the thing it was written for.
    """
    matched = HEALTHY + """\
      - uses: github/codeql-action/init@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4.38.2
      - uses: github/codeql-action/analyze@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4.38.2
"""
    write_workflow(tmp_path, "ci.yml", matched)
    assert conditions(gate, tmp_path, checks=[gate.check_action_pins]) == []

    split = matched.replace(
        "analyze@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4.38.2",
        "analyze@6f5948dfacef28e207b48d0905cf90c03365536d # v3.37.9",
    )
    write_workflow(tmp_path, "ci.yml", split)
    assert "split action version" in conditions(
        gate, tmp_path, checks=[gate.check_action_pins]
    ), "init and analyze are sub-actions of ONE repository and must share a release"


def test_two_different_repositories_at_different_refs_are_fine(gate, tmp_path):
    """The false-positive guard for the repository keying.

    `actions/checkout` and `actions/upload-artifact` are separate
    repositories that legitimately sit at different versions; grouping by
    owner alone would flag them.
    """
    body = HEALTHY + """\
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
"""
    write_workflow(tmp_path, "ci.yml", body)
    assert conditions(gate, tmp_path, checks=[gate.check_action_pins]) == []


def test_an_unpinned_reusable_workflow_call_is_reported(gate, tmp_path):
    """Job-level `uses:` is a reusable workflow, not a step.

    `jobs.<id>.uses: owner/repo/.github/workflows/ci.yml@main` never appears
    in `job.steps`, so iterating steps alone omitted it from the audit
    entirely -- and it runs with this repository's token.
    """
    write_workflow(tmp_path, "ci.yml", """\
name: ci
on:
  pull_request:
permissions:
  contents: read
jobs:
  call:
    uses: some-org/shared/.github/workflows/build.yml@main
""")
    failed = conditions(gate, tmp_path, checks=[gate.check_action_pins])
    assert "unpinned action" in failed, failed


def test_a_pinned_reusable_workflow_call_is_accepted(gate, tmp_path):
    """The same call pinned to a SHA with a version comment must pass."""
    write_workflow(tmp_path, "ci.yml", """\
name: ci
on:
  pull_request:
permissions:
  contents: read
jobs:
  call:
    uses: some-org/shared/.github/workflows/build.yml@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
""")
    assert conditions(gate, tmp_path, checks=[gate.check_action_pins]) == []


def test_missing_permissions_is_reported(gate, tmp_path):
    """No `permissions:` block means the token inherits the repo default."""
    write_workflow(tmp_path, "ci.yml",
                   HEALTHY.replace("permissions:\n  contents: read\n", ""))
    assert "missing permissions" in conditions(
        gate, tmp_path, checks=[gate.check_permissions])


def test_a_job_without_permissions_is_reported_even_when_a_sibling_has_them(
    gate, tmp_path
):
    """Job-level permissions configure jobs INDEPENDENTLY.

    With no workflow-level block and one job declaring its own, the earlier
    `any(...)` form reported the whole workflow as protected -- while the
    other job still received the repository default, which can be write-all.
    """
    write_workflow(tmp_path, "ci.yml", """\
name: ci
on:
  pull_request:
jobs:
  guarded:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  uncovered:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
""")
    findings = gate.Findings()
    gate.check_permissions(gate.load_workflows(tmp_path), findings)
    reported = [(i["condition"], i["where"]) for i in findings.failures]
    assert any(c == "missing permissions" and w.endswith(":uncovered")
               for c, w in reported), reported
    assert not any(w.endswith(":guarded") for _c, w in reported), reported


def test_a_workflow_level_block_covers_every_job(gate, tmp_path):
    """The false-positive guard: top-level permissions are inherited."""
    write_workflow(tmp_path, "ci.yml", """\
name: ci
on:
  pull_request:
permissions:
  contents: read
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
""")
    findings = gate.Findings()
    gate.check_permissions(gate.load_workflows(tmp_path), findings)
    assert findings.failures == [], findings.failures


def test_write_all_permissions_is_reported(gate, tmp_path):
    write_workflow(tmp_path, "ci.yml",
                   HEALTHY.replace("permissions:\n  contents: read",
                                   "permissions: write-all"))
    assert "permissions write-all" in conditions(
        gate, tmp_path, checks=[gate.check_permissions])


def test_pull_request_target_with_a_pr_head_checkout_is_reported(gate, tmp_path):
    """The standard CI takeover, which nothing else here looked for."""
    body = HEALTHY.replace("  pull_request:\n", "  pull_request_target:\n").replace(
        "      - name: test",
        "        with:\n"
        "          ref: ${{ github.event.pull_request.head.sha }}\n"
        "      - name: test",
    )
    write_workflow(tmp_path, "ci.yml", body)
    assert "pull_request_target checks out PR head" in conditions(
        gate, tmp_path, checks=[gate.check_pull_request_target])


def test_pull_request_target_without_a_head_checkout_is_allowed(gate, tmp_path):
    """`pull_request_target` alone is a legitimate pattern (labels, comments)."""
    write_workflow(tmp_path, "ci.yml",
                   HEALTHY.replace("  pull_request:\n", "  pull_request_target:\n"))
    assert conditions(gate, tmp_path,
                      checks=[gate.check_pull_request_target]) == []


def test_continue_on_error_on_a_gate_step_is_reported(gate, tmp_path):
    """A step that cannot fail is a notification, not a gate."""
    write_workflow(tmp_path, "ci.yml",
                   HEALTHY.replace("      - name: test\n        run: pytest -q",
                                   "      - name: test\n        continue-on-error: true\n"
                                   "        run: pytest -q"))
    assert "gate cannot fail" in conditions(
        gate, tmp_path, checks=[gate.check_gates_can_fail])


def test_continue_on_error_on_the_whole_job_is_reported(gate, tmp_path):
    write_workflow(tmp_path, "ci.yml",
                   HEALTHY.replace("    runs-on: ubuntu-latest",
                                   "    continue-on-error: true\n    runs-on: ubuntu-latest"))
    assert "gate cannot fail" in conditions(
        gate, tmp_path, checks=[gate.check_gates_can_fail])


def test_an_unparseable_workflow_is_a_failure_not_a_skip(gate, tmp_path):
    """Fail closed: a workflow nothing can read audits as nothing."""
    write_workflow(tmp_path, "ci.yml", "name: ci\n  bad:\n - indentation\n")
    assert "unparseable workflow" in conditions(
        gate, tmp_path, checks=[gate.check_action_pins])


# ---------------------------------------------------------------------------
# The CodeQL coherence conditions run against a synthetic tree, so they need
# the gate module importable from `scripts/youtab` -- which is why `root` is
# the real repository here and only the baselines are redirected.
# ---------------------------------------------------------------------------
def test_the_real_repository_passes_every_offline_condition(gate):
    """The conditions must hold for this repository as it stands.

    This is the one test that would have caught the state the gate was written
    for, and it is also the regression guard: a later change to a workflow, a
    pin, or a baseline that breaks a condition fails here rather than in CI.
    """
    findings = gate.Findings()
    workflows = gate.load_workflows(REPO_ROOT)
    assert workflows, "no workflows found in the repository"
    gate.check_action_pins(workflows, findings)
    gate.check_permissions(workflows, findings)
    gate.check_pull_request_target(workflows, findings)
    gate.check_gates_can_fail(workflows, findings)
    gate.check_codeql_coherence(REPO_ROOT, workflows, findings)
    assert findings.failures == [], json.dumps(findings.failures, indent=2)


def test_the_required_checks_condition_skips_rather_than_passes(gate, monkeypatch):
    """AGENTS.md: a blocked check must not become a PASS.

    Without a token the ruleset cannot be read. The condition must say so --
    reported as SKIPPED and counted separately -- and `--require-remote` must
    turn that into a failure for CI, where the token exists and a skip would
    mean the check silently stopped running.
    """
    monkeypatch.delenv("GH_TOKEN", raising=False)
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)

    findings = gate.Findings()
    gate.check_required_checks(REPO_ROOT, {}, "owner/repo", findings, False)
    assert findings.failures == []
    assert len(findings.skips) == 1
    assert "NOT evaluated" in findings.skips[0]["detail"]

    strict = gate.Findings()
    gate.check_required_checks(REPO_ROOT, {}, "owner/repo", strict, True)
    assert [i["condition"] for i in strict.failures] == ["ruleset unavailable"]


def test_a_codeql_leg_without_a_baseline_is_reported(gate, tmp_path, monkeypatch):
    """The gate step would otherwise fail every run with a path error."""
    root = tmp_path
    (root / "scripts" / "youtab" / "codeql_baselines").mkdir(parents=True)
    for name in ("codeql_sarif_gate.py", "regenerate_codeql_baseline.py"):
        (root / "scripts" / "youtab" / name).write_bytes(
            (REPO_ROOT / "scripts" / "youtab" / name).read_bytes()
        )
    write_workflow(root, "codeql.yml", """\
name: CodeQL
on:
  pull_request:
permissions:
  contents: read
jobs:
  analyze:
    name: CodeQL analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: python
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
""")
    findings = gate.Findings()
    gate.check_codeql_coherence(root, gate.load_workflows(root), findings)
    assert "codeql leg without a baseline" in [
        i["condition"] for i in findings.failures
    ], findings.failures


def test_a_baseline_without_a_severity_budget_is_reported(gate, tmp_path):
    """The ratchet lives in the baseline, so a missing budget removes it."""
    root = tmp_path
    baselines = root / "scripts" / "youtab" / "codeql_baselines"
    baselines.mkdir(parents=True)
    for name in ("codeql_sarif_gate.py", "regenerate_codeql_baseline.py"):
        (root / "scripts" / "youtab" / name).write_bytes(
            (REPO_ROOT / "scripts" / "youtab" / name).read_bytes()
        )
    (baselines / "python.json").write_text(json.dumps({
        "source_run": "https://example.test/run/1",
        "source_head": "0" * 40,
        "artifact_count": 1, "query_count": 1, "extracted_count": 1,
    }), encoding="utf-8")
    write_workflow(root, "codeql.yml", """\
name: CodeQL
on:
  pull_request:
permissions:
  contents: read
jobs:
  analyze:
    name: CodeQL analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: python
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
""")
    findings = gate.Findings()
    gate.check_codeql_coherence(root, gate.load_workflows(root), findings)
    reported = [i["condition"] for i in findings.failures]
    assert "baseline without a severity budget" in reported, findings.failures
